title: Solutions with Nabinte
author: NabinteDev
email: solutions@nabinte.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to our company Blog.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
